### ISSUE TITLE
example can't compile because esp32s-hal-common isn't the latest

### ISSUE THREAD

**Issue by maayanhaimdulberg** [esp-rs/esp-hal#863] opened 2023-10-22 14:09 UTC
example (and probably not only this one) https://github.com/esp-rs/esp-hal/blob/main/esp32s3-hal/examples/i2c_bmp180_calibration_data.rs can't compile.

I2C::new() introduces a new argument (PeripheralClockControl) in the newest esp32s-hal-common, but the newest example version isn't pointing to the latest one.

![image](https://github.com/esp-rs/esp-hal/assets/147316918/6d2fbe74-1e74-43be-9c53-04ba562f3ae5)

**Comment by bugadani** [comment] 2023-10-22 14:52
> I2C::new() introduces a new argument (PeripheralClockControl) in the newest esp32s-hal-common

This isn't correct, the argument was instead removed recently.

**Comment by bjoernQ** [comment] 2023-10-23 07:06
Our main branch is not the currently released version but the "next" version. The next release will contain a couple of breaking changes so examples in `main` won't currently work (see above)

(Closing this - feel free to re-open if you feel the issue isn't resolved)

**Closed by bjoernQ** 2023-10-23 07:06 UTC
