### ISSUE TITLE
A way to specify memory properties like flash size

### ISSUE THREAD

**Issue by bjoernQ** [esp-rs/esp-hal#42] opened 2022-04-05 13:39 UTC
It's very convenient that we don't need a `memory.x` or `build.rs` in binary crates using the HAL

However, we should be able to set things like flash size if it doesn't match our default.

Ideally not by providing custom linker scripts

**Comment by MabezDev** [comment] 2022-04-11 10:24
Perhaps a somewhat odd but simple strategy, what about setting the flash size to the addressable per chip and then letting the flashing step detect the failures?

E.g for the esp32 the max external flash supported is 16MB, we'd set that in the linker script. If someone tried to flash a 12MB program on a physical module with only 4MB the flashing step will fail.

**Comment by bjoernQ** [comment] 2023-03-07 14:45
Maybe flash size was not the best example. What about things like guaranteed allocated stack-size (which are not manageable in a sane way with cargo features)

**Comment by MabezDev** [comment] 2024-02-26 16:51
I think this is a duplicate of #1111, so lets continue the discussion there.

**Closed by MabezDev** 2024-02-26 16:51 UTC
Labels: enhancement, help wanted, good first issue
